name: Deploy to Azure

inputs:
  azure_credentials:
    description: JSON object containing a service principal that can read from Azure Key Vault
    required: true
  environment_name:
    description: The name of the environment
    required: true

outputs:
  environment_url:
    description: The base URL for the deployed environment
    value: ${{ steps.terraform.outputs.url }}

runs:
  using: composite

  steps:

   - uses: Azure/login@v1
     with:
       creds: ${{ inputs.azure_credentials }}

   - id: deploy-arm-resources
     run: |
       make ci ${{ inputs.environment_name }} deploy-azure-resources
     shell: bash
